export const EventTypes = {
  PROGRAM_CREATED: "PROGRAM_CREATED",
  SESSION_CREATED: "SESSION_CREATED",
  SESSION_REORDERED: "SESSION_REORDERED",
  SESSION_DELETED: "SESSION_DELETED",
  PASSWORD_RESETED: "PASSWORD_RESETED",
  BULK_SESSION_CREATED: "BULK_SESSION_CREATED",
  TENANT_CREATED: "TENANT_CREATED",
};
